In [2]:
import numpy as np
a=np.array([10,20,30,40,50])
mask=np.array([True,False,True,False,True])
a[mask]

array([10, 30, 50])

In [7]:
a=np.array([10,20,30,40,50])
idx=np.array([4,0,4,1])
a[idx]

array([50, 10, 50, 20])

In [14]:
a=np.array([1,2,3,4,5,6])
mask=np.array([True,False,True,False,True,False])
a[mask]

array([1, 3, 5])

In [17]:
a=np.array([[1,2],[3,4]])
b=np.array([10,20,30])
a+b

ValueError: operands could not be broadcast together with shapes (2,2) (3,) 

In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
print("a=",a)

a[:,[False,True]]


a= [[1 2]
 [3 4]
 [5 6]]


array([[2],
       [4],
       [6]])

In [ ]:
a[:,1]

array([2, 4, 6])

In [ ]:
a[:,0]

array([1, 3, 5])

In [15]:
a=np.array([[1,2,3],[3,4,5]])
b=np.array([10,20,30])
a[b]

IndexError: index 10 is out of bounds for axis 0 with size 2

In [18]:
a=np.array([[1,2,6],[3,4,5]])
b=np.array([10,20,30])
a+b

array([[11, 22, 36],
       [13, 24, 35]])

In [30]:
a=np.array([[1,2],[3,4]])
b=np.array([0,1])
a[b]

array([[1, 2],
       [3, 4]])

In [68]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([10,20,30])
print(a)
a+b


[[1 2 3]
 [4 5 6]]


array([[11, 22, 33],
       [14, 25, 36]])

In [69]:
a*b

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [74]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([1],
           [2],
           [3])
print(a.shape)
print(b.shape)
a*b

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [85]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[3],[4]])
print(a.shape)
print(b.shape)
a*b

(2, 3)
(2, 1)


array([[ 3,  6,  9],
       [16, 20, 24]])

In [83]:
a=np.array([1,2,3,4,5])
a[a>2]

array([3, 4, 5])

In [87]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[10],[20],[30]])
print(a.shape)
print(b.shape)
a+b

(2, 3)
(3, 1)


ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 